import { useState, useCallback, useEffect, useRef } from "react";
import { PEFF_SECTIONS } from "../data/peffSections.js";
import { PF_CATEGORIES, ALL_PROCESSES } from "../data/peffProcesos.js";
import { HelpTip, OptionHelpTip, renderGroupedCoord, TeethButton } from "./NewPEFF_helpers.jsx";
import PatientLookup from "./PatientLookup.jsx";
import AIReportPanel from "./AIReportPanel.jsx";
import { db, doc, updateDoc } from "../firebase.js";
import { fbAdd } from "../lib/fb.js";
import { saveDraft, deleteDraft } from "../lib/drafts.js";
import { detectProceso } from "../lib/detectProceso.js";
const K={mt:"#64748b"};
const gm=(b,e)=>{const B=new Date(b),E=new Date(e);let m=(E.getFullYear()-B.getFullYear())*12+E.getMonth()-B.getMonth();if(E.getDate()<B.getDate())m--;return Math.max(0,m)};
const fa=m=>`${Math.floor(m/12)} a\u00f1os, ${m%12} meses`;
const sevDesc={"Adecuado":"PCC = 100%: El ni\u00f1o/a produce correctamente todos los fonemas evaluados.","Leve":"PCC 85\u201399%: Errores articulatorios aislados, inteligibilidad conservada.","Leve-Moderado":"PCC 65\u201384%: M\u00faltiples errores, inteligibilidad parcialmente afectada.","Moderado-Severo":"PCC 50\u201364%: Errores frecuentes, inteligibilidad comprometida.","Severo":"PCC <50%: Errores generalizados, inteligibilidad severamente afectada."};
const sevColor={"Adecuado":"#059669","Leve":"#84cc16","Leve-Moderado":"#f59e0b","Moderado-Severo":"#ea580c","Severo":"#dc2626"};
const speak=(text)=>{if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="es-AR";u.rate=0.68;u.pitch=1.08;u.volume=1;const voices=window.speechSynthesis.getVoices();const pick=voices.find(v=>/es[-_]AR/i.test(v.lang)&&/female|Google|Microsoft/i.test(v.name))||voices.find(v=>/es[-_]AR/i.test(v.lang))||voices.find(v=>/es[-_]MX/i.test(v.lang))||voices.find(v=>/es[-_]ES/i.test(v.lang))||voices.find(v=>v.lang.startsWith("es"));if(pick)u.voice=pick;window.speechSynthesis.speak(u)};
const scrollTop=()=>{const el=document.getElementById("main-scroll");if(el)el.scrollTo({top:0,behavior:"smooth"});else window.scrollTo({top:0,behavior:"smooth"})};
const RESULT_STEP=PEFF_SECTIONS.length+1;
export default function NewPEFF({onS,nfy,userId,draft,therapistInfo}){
var init=draft?draft.data:null;
const[step,setStep]=useState(init?(init.step||0):0),[pd,sPd]=useState(init?init.pd:{pN:"",birth:"",eD:new Date().toISOString().split("T")[0],sch:"",ref:"",obs:"",dni:""}),[data,setD]=useState(init?(init.data||{}):{}),[procData,setProcData]=useState(init?(init.procData||{}):{});
const[playingId,setPlayingId]=useState(null),[selectedPatient,setSelectedPatient]=useState(init?init.selectedPatient:null);
const[saved,setSaved]=useState(false),[savedDocId,setSavedDocId]=useState(null),[report,setReport]=useState(null),[showTech,setShowTech]=useState(false);
const docIdRef=useRef(null);
const a=pd.birth&&pd.eD?gm(pd.birth,pd.eD):0;
const I={width:"100%",padding:"10px 14px",border:"1px solid #e2e8f0",borderRadius:8,fontSize:14,background:"#f8faf9"};
const sf=(id,v)=>setD(p=>({...p,[id]:v}));
const spf=(itemId,field,v)=>setProcData(p=>({...p,[itemId]:{...(p[itemId]||{}),[field]:v}}));
var handlePatientSelect=function(pac){setSelectedPatient(pac);if(pac){sPd(function(p){return Object.assign({},p,{pN:pac.nombre||"",birth:pac.fechaNac||"",sch:pac.colegio||"",dni:pac.dni||""})});}else{sPd(function(p){return Object.assign({},p,{pN:"",birth:"",sch:"",dni:""})});}};
useEffect(()=>{scrollTop()},[step]);
useEffect(()=>{if(window.speechSynthesis){window.speechSynthesis.getVoices();window.speechSynthesis.onvoiceschanged=()=>window.speechSynthesis.getVoices()}},[]);
useEffect(function(){if(step===RESULT_STEP&&!saved){var r=calc();var payload={id:Date.now()+"",userId:userId,tipo:"peff",paciente:pd.pN,pacienteDni:pd.dni||"",fechaNacimiento:pd.birth,fechaEvaluacion:pd.eD,establecimiento:pd.sch,derivadoPor:pd.ref,edadMeses:a,observaciones:pd.obs||"",evaluador:"",fechaGuardado:new Date().toISOString(),seccionData:data,procesosData:procData,resultados:r};fbAdd("evaluaciones",payload).then(function(res){if(res.success){docIdRef.current=res.id;setSavedDocId(res.id);nfy("PEFF guardada","ok")}else nfy("Error: "+res.error,"er")});if(draft&&draft._fbId)deleteDraft(draft._fbId);setSaved(true)}},[step]);
const goStep=(s)=>{setStep(s);scrollTop()};
const handlePausePEFF=()=>{
  var draftData={step,pd,data,procData,selectedPatient,patientId:selectedPatient?(selectedPatient._fbId||selectedPatient.dni||pd.pN):"unknown"};
  saveDraft(userId,"peff",draftData).then(r=>{if(r.success)nfy("Evaluacion pausada","ok");onS("tools")});
};
const handleFinishEarlyPEFF=()=>{
  if(!selectedPatient){nfy("Selecciona un paciente","er");return;}
  if(Object.keys(data).length===0){nfy("Registra al menos una respuesta","er");return;}
  if(window.confirm("Finalizar evaluacion ahora?\n\nSe guardaran los datos registrados hasta el momento."))goStep(RESULT_STEP);
};
const rField=(f,opts)=>{const hideHelp=opts?.hideHelp;if(f.type==="text")return <div key={f.id} style={{marginBottom:14}}><label style={{fontSize:12,fontWeight:600,color:K.mt,display:"block",marginBottom:4}}>{f.label}{!hideHelp&&<HelpTip text={f.help} searchTerm={f.label}/>}{f.showTeethImg&&<TeethButton arch={f.showTeethImg} ageMo={a}/>}</label><input value={data[f.id]||""} onChange={e=>sf(f.id,e.target.value)} style={I}/></div>;const cur=data[f.id]||"";return <div key={f.id} style={{marginBottom:14}}><label style={{fontSize:12,fontWeight:600,color:K.mt,display:"block",marginBottom:6}}>{f.label}{!hideHelp&&<HelpTip text={f.help} searchTerm={f.label}/>}</label>{f.desc&&<div style={{fontSize:11,color:"#7c3aed",marginBottom:6,fontStyle:"italic"}}>{f.desc}</div>}<div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{f.options.map(o=><span key={o} style={{display:"inline-flex",alignItems:"center"}}><button onClick={()=>sf(f.id,cur===o?"":o)} style={{padding:"8px 14px",borderRadius:8,border:cur===o?"2px solid #7c3aed":"1px solid #e2e8f0",background:cur===o?"#ede9fe":"#fff",color:cur===o?"#5b21b6":"#475569",fontSize:13,fontWeight:cur===o?700:400,cursor:"pointer",transition:"all .15s",textAlign:"left"}}>{cur===o&&"\u2713 "}{o}</button>{f.optionHelp&&f.optionHelp[o]&&<OptionHelpTip text={f.optionHelp[o]} label={o}/>}</span>)}</div></div>};
const legendItems=[{v:"\u2713",bg:"#059669",t:"Correcto",d:"Producci\u00f3n adecuada"},{v:"D",bg:"#f59e0b",t:"Distorsi\u00f3n",d:"Sonido alterado"},{v:"O",bg:"#dc2626",t:"Omisi\u00f3n",d:"No produce"},{v:"S",bg:"#7c3aed",t:"Sustituci\u00f3n",d:"Reemplaza"}];
const legendBox=<div style={{background:"#ede9fe",border:"1px solid #c4b5fd",borderRadius:10,padding:14}}><div style={{fontSize:12,fontWeight:700,color:"#5b21b6",marginBottom:8}}>Leyenda</div><div style={{display:"flex",flexDirection:"column",gap:6}}>{legendItems.map(o=><div key={o.v} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:24,height:24,borderRadius:6,background:o.bg,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:700,flexShrink:0}}>{o.v}</div><span style={{fontSize:12}}><b>{o.t}</b> {"\u2014"} {o.d}</span></div>)}</div></div>;
const rPhon=item=>{const v=data[item.id]||"";const isError=v==="D"||v==="O"||v==="S";const pd2=procData[item.id]||{};return<div key={item.id} style={{marginBottom:isError?12:4}}><div style={{display:"flex",alignItems:"center",gap:10,padding:"8px 14px",background:isError?"#fef2f2":v==="ok"?"#f0fdf4":"#fff",borderRadius:isError?"8px 8px 0 0":8,border:`1px solid ${isError?"#fecaca":v==="ok"?"#bbf7d0":"#e2e8f0"}`}}><span style={{fontWeight:700,fontSize:16,minWidth:50,color:"#7c3aed"}}>{item.word}</span><span style={{fontSize:12,color:K.mt,flex:1}}>{item.target}</span><div style={{display:"flex",gap:4}}>{[{v:"ok",l:"\u2713",bg:"#059669"},{v:"D",l:"D",bg:"#f59e0b"},{v:"O",l:"O",bg:"#dc2626"},{v:"S",l:"S",bg:"#7c3aed"}].map(o=><button key={o.v} onClick={()=>{sf(item.id,v===o.v?"":o.v);if(o.v==="ok")setProcData(p=>{const n={...p};delete n[item.id];return n})}} style={{width:30,height:30,borderRadius:6,border:v===o.v?`2px solid ${o.bg}`:"1px solid #e2e8f0",background:v===o.v?o.bg:"#fff",color:v===o.v?"#fff":"#64748b",fontSize:12,fontWeight:700,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"}}>{o.l}</button>)}</div></div>{isError&&<div style={{background:"#fff5f5",border:"1px solid #fecaca",borderTop:"none",borderRadius:"0 0 8px 8px",padding:"10px 14px"}}><div style={{display:"flex",gap:8,marginBottom:6,flexWrap:"wrap"}}><div style={{flex:1,minWidth:180}}><label style={{fontSize:10,fontWeight:700,color:"#dc2626",display:"block",marginBottom:3}}>{"Producci\u00f3n del ni\u00f1o"}</label><input value={pd2.produccion||""} onChange={e=>{var val=e.target.value;spf(item.id,"produccion",val);var detected=detectProceso(item.word,val,v);if(detected&&!(pd2.proceso&&pd2.manualProceso)){spf(item.id,"proceso",detected);spf(item.id,"autoDetected",true)}}} style={{...I,fontSize:13,padding:"6px 10px",background:"#fff"}} placeholder={`Qu\u00e9 dijo en vez de "${item.word}"?`}/></div><div style={{flex:2,minWidth:220}}><label style={{fontSize:10,fontWeight:700,color:"#dc2626",display:"block",marginBottom:3}}>{"Proceso fonol\u00f3gico"}{pd2.autoDetected&&!pd2.manualProceso&&<span style={{marginLeft:6,fontSize:9,color:"#7c3aed",background:"#ede9fe",padding:"1px 6px",borderRadius:4,fontWeight:600}}>{"auto"}</span>}</label><select value={pd2.proceso||""} onChange={e=>{spf(item.id,"proceso",e.target.value);spf(item.id,"manualProceso",true);spf(item.id,"autoDetected",false)}} style={{...I,fontSize:13,padding:"6px 10px",background:pd2.autoDetected&&!pd2.manualProceso?"#f5f3ff":"#fff",cursor:"pointer",borderColor:pd2.autoDetected&&!pd2.manualProceso?"#a78bfa":"#e2e8f0"}}><option value="">-- Clasificar --</option>{PF_CATEGORIES.map(cat=><optgroup key={cat.id} label={cat.title}>{cat.processes.map(pr=><option key={pr.id} value={pr.id}>{pr.name}</option>)}</optgroup>)}</select></div></div>{pd2.proceso&&<div style={{fontSize:11,color:"#7c3aed",fontStyle:"italic",marginTop:2}}>{ALL_PROCESSES.find(p=>p.id===pd2.proceso)?.desc||""}</div>}</div>}</div>};
const rDisc=item=>{const v=data[item.id]||"";return<div key={item.id} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 14px",background:v==="correcto"?"#f0fdf4":v==="incorrecto"?"#fef2f2":"#fff",borderRadius:8,border:`1px solid ${v==="correcto"?"#bbf7d0":v==="incorrecto"?"#fecaca":"#e2e8f0"}`,marginBottom:4}}><span style={{fontWeight:600,fontSize:14,flex:1}}>{item.pair}</span>{item.contrast&&<span style={{fontSize:11,color:K.mt}}>{item.contrast}</span>}<div style={{display:"flex",gap:4}}>{["correcto","incorrecto"].map(o=><button key={o} onClick={()=>sf(item.id,v===o?"":o)} style={{padding:"5px 10px",borderRadius:6,border:v===o?`2px solid ${o==="correcto"?"#059669":"#dc2626"}`:"1px solid #e2e8f0",background:v===o?(o==="correcto"?"#059669":"#dc2626"):"#fff",color:v===o?"#fff":"#64748b",fontSize:12,fontWeight:600,cursor:"pointer"}}>{o==="correcto"?"\u2714":"\u2718"}</button>)}</div></div>};
const rRec=item=>{const v=data[item.id]||"";const parts=item.target.split("/");const word1=(parts[0]||"").trim();const word2=(parts[1]||"").trim();const correctWord=word1;const isPlaying=playingId===item.id;const handleSpeak=()=>{setPlayingId(item.id);speak(correctWord);setTimeout(()=>setPlayingId(null),1500)};const handleSelect=(sw)=>{sf(item.id,sw===correctWord?"reconoce":"no")};const options=item.id.charCodeAt(item.id.length-1)%2===0?[word1,word2]:[word2,word1];return<div key={item.id} style={{padding:"12px 16px",background:v==="reconoce"?"#f0fdf4":v==="no"?"#fef2f2":"#fff",borderRadius:10,border:`1px solid ${v==="reconoce"?"#bbf7d0":v==="no"?"#fecaca":"#e2e8f0"}`,marginBottom:6}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:v?4:0}}><button onClick={handleSpeak} style={{background:isPlaying?"#7c3aed":"#ede9fe",color:isPlaying?"#fff":"#7c3aed",border:"1px solid #c4b5fd",borderRadius:8,padding:"8px 14px",fontSize:13,fontWeight:600,cursor:"pointer",flexShrink:0}}>{isPlaying?"\ud83d\udd0a ...":"\ud83d\udd0a Escuchar"}</button><span style={{fontSize:11,color:K.mt,flex:1}}>{item.contrast}</span><div style={{display:"flex",gap:6}}>{options.map(w=>{const isSel=(v==="reconoce"&&w===correctWord)||(v==="no"&&w!==correctWord);const isCorr=v&&w===correctWord;return<button key={w} onClick={()=>handleSelect(w)} style={{padding:"8px 18px",borderRadius:8,fontSize:14,fontWeight:700,cursor:"pointer",border:isSel?`2px solid ${isCorr?"#059669":"#dc2626"}`:`2px solid #e2e8f0`,background:isSel?(isCorr?"#059669":"#dc2626"):"#fff",color:isSel?"#fff":"#1e293b",opacity:v&&!isSel?0.5:1}}>{w}</button>})}</div>{v&&<button onClick={()=>{const n={...data};delete n[item.id];setD(n)}} style={{background:"none",border:"none",color:"#94a3b8",fontSize:16,cursor:"pointer",padding:4}}>{"\u00d7"}</button>}</div>{v&&<div style={{fontSize:11,marginTop:4,paddingLeft:4,color:v==="reconoce"?"#059669":"#dc2626",fontWeight:600}}>{v==="reconoce"?"\u2713 Reconoce correctamente":"\u2717 No reconoce"}</div>}</div>};
const rSec=sec=>{const isFon=sec.id==="fon";const isCoord=sec.id==="cnm";const isRecFon=sec.id==="recfon";const mainContent=<div style={isFon?{flex:1,minWidth:0}:{}}><h2 style={{fontSize:18,fontWeight:700,marginBottom:4,color:"#7c3aed"}}>{sec.title}</h2>{sec.description&&<p style={{color:K.mt,fontSize:13,marginBottom:16}}>{sec.description}</p>}{isRecFon&&<div style={{background:"#f0f9ff",border:"1px solid #bae6fd",borderRadius:8,padding:12,marginBottom:16,fontSize:12,color:"#0369a1",lineHeight:1.6}}><strong>{"\ud83c\udfa7 Instrucciones:"}</strong>{" Presione \"Escuchar\" para reproducir la palabra. El ni\u00f1o/a debe se\u00f1alar cu\u00e1l corresponde."}</div>}{sec.subsections.map(sub=><div key={sub.id} style={{marginBottom:20}}><h3 style={{fontSize:15,fontWeight:600,marginBottom:10,color:"#0a3d2f",paddingBottom:6,borderBottom:"2px solid #ede9fe"}}>{sub.title}</h3>{sub.fields&&(isCoord?renderGroupedCoord(sub.fields,rField):sub.fields.map(f=>rField(f)))}{sub.items&&sub.items.map(i=>rPhon(i))}{sub.discItems&&sub.discItems.map(i=>rDisc(i))}{sub.recItems&&sub.recItems.map(i=>rRec(i))}</div>)}</div>;if(!isFon)return mainContent;return <div style={{display:"flex",gap:16,alignItems:"flex-start"}}>{mainContent}<div style={{width:260,flexShrink:0,position:"sticky",top:16,alignSelf:"flex-start"}}>{legendBox}</div></div>};
const countUnevalSelects=()=>{let c=0;PEFF_SECTIONS.forEach(sec=>{sec.subsections.forEach(sub=>{if(sub.fields)sub.fields.forEach(f=>{if(f.type==="select"&&!data[f.id])c++})})});return c};
const countUnevalPhon=()=>{let c=0;const s=PEFF_SECTIONS.find(s=>s.id==="fon");if(s)s.subsections.forEach(sub=>{if(sub.items)sub.items.forEach(i=>{if(!data[i.id])c++})});return c};
const countUnevalDisc=()=>{let c=0;const s=PEFF_SECTIONS.find(s=>s.id==="disc");if(s)s.subsections.forEach(sub=>{if(sub.discItems)sub.discItems.forEach(i=>{if(!data[i.id])c++})});return c};
const countUnevalRec=()=>{let c=0;const s=PEFF_SECTIONS.find(s=>s.id==="recfon");if(s)s.subsections.forEach(sub=>{if(sub.recItems)sub.recItems.forEach(i=>{if(!data[i.id])c++})});return c};
const calc=()=>{const sI=PEFF_SECTIONS.find(s=>s.id==="fon")?.subsections.flatMap(sub=>sub.items||[])||[];const sOk=sI.filter(i=>data[i.id]==="ok").length;const sEvaluated=sI.filter(i=>!!data[i.id]).length;const sPct=sI.length?Math.round(sOk/sI.length*100):0;const sPctEval=sEvaluated>0?Math.round(sOk/sEvaluated*100):0;const dI=PEFF_SECTIONS.find(s=>s.id==="disc")?.subsections.flatMap(sub=>sub.discItems||[])||[];const dOk=dI.filter(i=>data[i.id]==="correcto").length;const dEval=dI.filter(i=>!!data[i.id]).length;const dPct=dEval>0?Math.round(dOk/dEval*100):0;const rI=PEFF_SECTIONS.find(s=>s.id==="recfon")?.subsections.flatMap(sub=>sub.recItems||[])||[];const rOk=rI.filter(i=>data[i.id]==="reconoce").length;const rEval=rI.filter(i=>!!data[i.id]).length;const rPct=rEval>0?Math.round(rOk/rEval*100):0;let sev="Adecuado";if(sPctEval<50)sev="Severo";else if(sPctEval<65)sev="Moderado-Severo";else if(sPctEval<85)sev="Leve-Moderado";else if(sPctEval<100)sev="Leve";const procAnalysis={byCategory:{},byProcess:{},errors:[],total:0};Object.entries(procData).forEach(([itemId,pd2])=>{if(!pd2.proceso)return;const proc=ALL_PROCESSES.find(p=>p.id===pd2.proceso);if(!proc)return;procAnalysis.total++;procAnalysis.byCategory[proc.category]=(procAnalysis.byCategory[proc.category]||0)+1;procAnalysis.byProcess[proc.id]=(procAnalysis.byProcess[proc.id]||0)+1;const item=sI.find(i=>i.id===itemId);procAnalysis.errors.push({itemId,word:item?.word||itemId,target:item?.target||"",produccion:pd2.produccion||"",proceso:proc.id,procesoName:proc.name,category:proc.category,categoryTitle:proc.categoryTitle,expectedAge:proc.expectedAge})});const us=countUnevalSelects(),up=countUnevalPhon(),ud=countUnevalDisc(),ur=countUnevalRec();return{silOk:sOk,silTotal:sI.length,silPct:sPct,silEval:sEvaluated,silPctEval:sPctEval,discOk:dOk,discTotal:dI.length,discEval:dEval,discPct:dPct,recOk:rOk,recTotal:rI.length,recEval:rEval,recPct:rPct,severity:sev,procAnalysis,pcc:sPctEval,unevalSelects:us,unevalPhon:up,unevalDisc:ud,unevalRec:ur,unevalTotal:us+up+ud+ur}};
const ResultCard=({title,desc,ok,total,evaluated,pct,color})=><div style={{background:"#f8faf9",borderRadius:12,padding:20,border:"1px solid #e2e8f0"}}><div style={{fontSize:14,fontWeight:700,color:"#1e293b",marginBottom:4}}>{title}</div><div style={{fontSize:11,color:K.mt,marginBottom:12,lineHeight:1.5}}>{desc}</div><div style={{fontSize:36,fontWeight:700,color:color||"#7c3aed",textAlign:"center"}}>{ok}<span style={{fontSize:16,color:K.mt}}>{"/"}{total}</span></div>{pct!==undefined&&<div style={{textAlign:"center",fontSize:13,color:K.mt,marginTop:4}}>{pct}{"% correcto"}</div>}{evaluated!==undefined&&evaluated<total&&<div style={{textAlign:"center",fontSize:11,color:"#f59e0b",marginTop:4}}>{"("}{evaluated}{" evaluados de "}{total}{")"}</div>}</div>;
return<div style={{width:"100%",maxWidth:1200,animation:"fi .3s ease"}}><div style={{display:"flex",gap:2,marginBottom:22}}>{["Datos",...PEFF_SECTIONS.map((_,i)=>`${i+1}`),"Result"].map((s,i)=><div key={i} style={{flex:1,textAlign:"center"}}><div style={{height:4,borderRadius:2,marginBottom:4,background:step>i?"#7c3aed":step===i?"#c4b5fd":"#e2e8f0"}}/><span style={{fontSize:9,color:step===i?"#7c3aed":"#64748b"}}>{s}</span></div>)}</div><div style={{background:"#fff",borderRadius:12,padding:28,border:"1px solid #e2e8f0"}}>
{step===0&&<div><h2 style={{fontSize:18,fontWeight:700,marginBottom:4,color:"#7c3aed"}}>{"PEFF \u2014 Datos del Paciente"}</h2><p style={{color:K.mt,fontSize:13,marginBottom:16}}>{"Protocolo de Evaluaci\u00f3n Fon\u00e9tico-Fonol\u00f3gica"}</p><PatientLookup userId={userId} onSelect={handlePatientSelect} selected={selectedPatient} color="#7c3aed" />{selectedPatient&&<div style={{marginTop:16}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><div><label style={{fontSize:12,fontWeight:600,color:K.mt,display:"block",marginBottom:4}}>{"Fecha de evaluaci\u00f3n"}</label><input type="date" value={pd.eD} onChange={e=>sPd(p=>({...p,eD:e.target.value}))} style={I}/></div><div><label style={{fontSize:12,fontWeight:600,color:K.mt,display:"block",marginBottom:4}}>{"Derivado por"}</label><input value={pd.ref} onChange={e=>sPd(p=>({...p,ref:e.target.value}))} style={I}/></div></div></div>}<div style={{display:"flex",justifyContent:"flex-end",marginTop:20}}><button onClick={()=>{if(!selectedPatient){nfy("Busque y seleccione un paciente","er");return}goStep(1)}} style={{background:"#7c3aed",color:"#fff",border:"none",padding:"10px 22px",borderRadius:8,fontSize:14,fontWeight:600,cursor:"pointer"}}>{"Siguiente \u2192"}</button></div></div>}
{step>=1&&step<=PEFF_SECTIONS.length&&rSec(PEFF_SECTIONS[step-1])}
{step===RESULT_STEP&&(()=>{const r=calc();const sc=sevColor[r.severity]||"#7c3aed";return<div>
<div style={{background:"#dcfce7",borderRadius:10,padding:"12px 18px",marginBottom:16,display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:18}}>{"\u2705"}</span><span style={{fontSize:13,fontWeight:600,color:"#059669"}}>{"Evaluación guardada correctamente."}</span></div>
<AIReportPanel ev={{_fbId:docIdRef.current,paciente:pd.pN,pacienteDni:pd.dni||"",edadMeses:a,fechaEvaluacion:pd.eD,derivadoPor:pd.ref,observaciones:pd.obs||"",resultados:calc(),aiReport:report}} evalType="peff" collectionName="evaluaciones" evalLabel="PEFF" autoGenerate={true} therapistInfo={therapistInfo} />
<button onClick={function(){setShowTech(!showTech)}} style={{width:"100%",padding:"14px",background:showTech?"#f1f5f9":"#0a3d2f",color:showTech?"#1e293b":"#fff",border:"1px solid #e2e8f0",borderRadius:10,fontSize:14,fontWeight:600,cursor:"pointer",marginBottom:showTech?16:20}}>{showTech?"\u25b2 Ocultar datos técnicos":"\u25bc Ver datos técnicos"}</button>
{showTech&&<div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:14,marginBottom:20}}><ResultCard title="Producci\u00f3n de S\u00edlabas" desc="S\u00edlabas correctas." ok={r.silOk} total={r.silTotal} evaluated={r.silEval} pct={r.silPctEval} color={r.silPctEval>=85?"#059669":r.silPctEval>=50?"#f59e0b":"#dc2626"}/><ResultCard title="Discriminaci\u00f3n Auditiva" desc="Pares diferenciados." ok={r.discOk} total={r.discTotal} evaluated={r.discEval} pct={r.discPct} color={r.discPct>=85?"#059669":r.discPct>=50?"#f59e0b":"#dc2626"}/><ResultCard title="Reconocimiento Fonol\u00f3gico" desc="Palabras identificadas." ok={r.recOk} total={r.recTotal} evaluated={r.recEval} pct={r.recPct} color={r.recPct>=85?"#059669":r.recPct>=50?"#f59e0b":"#dc2626"}/></div><div style={{background:`linear-gradient(135deg,${sc}dd,${sc})`,borderRadius:12,padding:24,color:"#fff",marginBottom:20}}><div style={{fontSize:13,opacity:.8,marginBottom:4}}>{"Severidad \u2014 PCC"}</div><div style={{fontSize:36,fontWeight:700}}>{r.severity}</div><div style={{fontSize:13,opacity:.9,lineHeight:1.6}}>{sevDesc[r.severity]}</div></div>{r.unevalTotal>0&&<div style={{background:"#fffbeb",border:"1px solid #fde68a",borderRadius:10,padding:16,marginBottom:20}}><div style={{fontSize:13,fontWeight:700,color:"#92400e",marginBottom:8}}>{"Items sin evaluar ("}{r.unevalTotal}{")"}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,fontSize:12,color:"#78350f"}}>{r.unevalSelects>0&&<div>{"OFA/Coord: "}<b>{r.unevalSelects}</b></div>}{r.unevalPhon>0&&<div>{"S\u00edlabas: "}<b>{r.unevalPhon}</b></div>}{r.unevalDisc>0&&<div>{"Disc: "}<b>{r.unevalDisc}</b></div>}{r.unevalRec>0&&<div>{"Reco: "}<b>{r.unevalRec}</b></div>}</div></div>}</div>}
<button onClick={()=>onS("tools")} style={{width:"100%",padding:"14px",background:"#7c3aed",color:"#fff",border:"none",borderRadius:10,fontSize:15,fontWeight:700,cursor:"pointer",marginTop:4}}>{"Finalizar \u2713"}</button>
</div>})()}
{step>=1&&step<=PEFF_SECTIONS.length&&<div style={{display:"flex",justifyContent:"space-between",marginTop:20,paddingTop:14,borderTop:"1px solid #e2e8f0",flexWrap:"wrap",gap:8}}><button onClick={()=>goStep(step-1)} style={{background:"#f1f5f9",border:"none",padding:"10px 22px",borderRadius:8,fontSize:14,fontWeight:600,cursor:"pointer"}}>{"Atras"}</button><div style={{display:"flex",gap:8}}><button onClick={handleFinishEarlyPEFF} style={{background:"#059669",color:"#fff",border:"none",padding:"10px 16px",borderRadius:8,fontSize:12,fontWeight:600,cursor:"pointer"}}>{"Finalizar ahora"}</button><button onClick={handlePausePEFF} style={{background:"#f59e0b",color:"#fff",border:"none",padding:"10px 16px",borderRadius:8,fontSize:12,fontWeight:600,cursor:"pointer"}}>{"Pausar"}</button><button onClick={()=>goStep(step+1)} style={{background:"#7c3aed",color:"#fff",border:"none",padding:"10px 22px",borderRadius:8,fontSize:14,fontWeight:600,cursor:"pointer"}}>{"Siguiente"}</button></div></div>}
</div></div>;
}
