import { useState } from "react";
const K = { mt: "#64748b" };
const fa=m=>`${Math.floor(m/12)} años, ${m%12} meses`;

export default function RptPEFF({ev,isA,onD}){
  const[cd,sCD]=useState(false);const r=ev.resultados||{};
  const pdf=()=>{const w=window.open("","_blank");if(!w)return;const d=ev.seccionData||{};
    const ofaFields=[["Labios postura",d.lab_postura],["Labios simetría",d.lab_simetria],["Tonicidad",d.lab_tonicidad],["ATM postura",d.atm_postura],["ATM apertura",d.atm_apertura],["Lengua postura",d.len_postura],["Lengua tamaño",d.len_tamano],["Frenillo",d.len_frenillo],["Dentición",d.die_denticion],["Angle Der.",d.die_angle_der],["Angle Izq.",d.die_angle_izq],["Mordida",d.die_mordida],["Paladar",d.pal_altura],["Integridad",d.pal_integridad],["Velo",d.vel_simetria],["Úvula",d.vel_uvula],["Escape nasal",d.vel_escape]].filter(([,v])=>v);
    const ofaHTML=ofaFields.map(([l,v])=>`<tr><td style="text-align:left;font-weight:600">${l}</td><td>${v}</td></tr>`).join("");
    w.document.write(`<!DOCTYPE html><html><head><title>PEFF ${ev.paciente}</title><style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:sans-serif;color:#1e293b;padding:24px 36px;max-width:800px;margin:0 auto;line-height:1.5}h1{font-size:22px;color:#5b21b6;border-bottom:3px solid #7c3aed;padding-bottom:8px;margin-bottom:18px}h2{font-size:14px;color:#5b21b6;margin:16px 0 8px;text-transform:uppercase}table{width:100%;border-collapse:collapse;margin:8px 0}th,td{border:1px solid #e2e8f0;padding:8px 12px;font-size:13px}th{background:#5b21b6;color:white}.res{background:#ede9fe;padding:12px;border-radius:8px;margin:8px 0}.ob{background:#f8faf9;padding:10px;border-radius:6px;border:1px solid #e2e8f0;font-size:13px;min-height:40px;margin:8px 0}.ft{margin-top:20px;border-top:1px solid #e2e8f0;padding-top:20px;display:flex;justify-content:space-between}.sg{text-align:center;width:44%}.sg .ln{border-top:1px solid #1e293b;margin-top:30px;padding-top:4px;font-size:12px}</style></head><body><div style="text-align:center;margin-bottom:28px"><h1 style="border:none;font-size:24px">INFORME PEFF</h1><p style="color:#64748b;font-size:13px">Brújula KIT</p></div><h2>Identificación</h2><table><tr><th>Nombre</th><td>${ev.paciente}</td><th>Edad</th><td>${fa(ev.edadMeses)}</td></tr><tr><th>F.nac</th><td>${ev.fechaNacimiento}</td><th>F.eval</th><td>${ev.fechaEvaluacion}</td></tr></table><h2>Examen OFA</h2><table><tr><th>Estructura</th><th>Hallazgo</th></tr>${ofaHTML||"<tr><td colspan=2>—</td></tr>"}</table><h2>Resultados</h2><div class="res"><strong>Sílabas:</strong> ${r.silOk||0}/${r.silTotal||0} (${r.silPct||0}%)<br><strong>Discriminación:</strong> ${r.discOk||0}/${r.discTotal||0}<br><strong>Reconocimiento:</strong> ${r.recOk||0}/${r.recTotal||0}</div><h2>Severidad</h2><div class="res" style="font-size:18px;font-weight:700;color:#5b21b6">${r.severity||"—"}</div><h2>Observaciones</h2><div class="ob">${ev.observaciones||"Sin observaciones."}</div><div class="ft"><div class="sg"><div class="ln">Firma Profesional</div></div><div class="sg"><div class="ln">Fecha</div><p style="font-size:11px">${new Date(ev.fechaGuardado).toLocaleDateString("es-CL")}</p></div></div></body></html>`);
    w.document.close();setTimeout(()=>w.print(),500)};
  return(<div style={{width:"100%",maxWidth:900,animation:"fi .3s ease"}}>
    <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:24,flexWrap:"wrap",gap:12}}>
      <div><h1 style={{fontSize:24,fontWeight:700,color:"#7c3aed"}}>Informe PEFF</h1><p style={{color:K.mt,fontSize:15,marginTop:2}}>{ev.paciente} — {fa(ev.edadMeses)}</p></div>
      <div style={{display:"flex",gap:8}}>
        {isA&&(cd?<div style={{display:"flex",gap:4}}><button onClick={()=>{onD(ev._fbId,"peff_evaluaciones");sCD(false)}} style={{background:"#dc2626",color:"#fff",border:"none",padding:"8px 16px",borderRadius:6,fontSize:12,fontWeight:600,cursor:"pointer"}}>Sí</button><button onClick={()=>sCD(false)} style={{background:"#f1f5f9",border:"none",padding:"8px 16px",borderRadius:6,fontSize:12,cursor:"pointer"}}>No</button></div>:<button onClick={()=>sCD(true)} style={{background:"#fef2f2",color:"#dc2626",border:"1px solid #fecaca",padding:"8px 16px",borderRadius:8,fontSize:13,cursor:"pointer"}}>🗑</button>)}
        <button onClick={pdf} style={{background:"#7c3aed",color:"#fff",border:"none",padding:"11px 22px",borderRadius:8,fontSize:14,fontWeight:600,cursor:"pointer"}}>📄 PDF</button>
      </div>
    </div>
    <div style={{background:"#fff",borderRadius:14,padding:32,border:"1px solid #e2e8f0"}}>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:14,marginBottom:20}}>{[["Sílabas",`${r.silOk||0}/${r.silTotal||0}`,`${r.silPct||0}%`],["Discriminación",`${r.discOk||0}/${r.discTotal||0}`,""],["Reconocimiento",`${r.recOk||0}/${r.recTotal||0}`,""]].map(([l,v,v2],i)=><div key={i} style={{background:"#f8faf9",borderRadius:10,padding:20,border:"1px solid #e2e8f0",textAlign:"center"}}><div style={{fontSize:11,color:K.mt,marginBottom:4}}>{l}</div><div style={{fontSize:28,fontWeight:700,color:"#7c3aed"}}>{v}</div>{v2&&<div style={{fontSize:13,color:K.mt}}>{v2}</div>}</div>)}</div>
      <div style={{background:"linear-gradient(135deg,#5b21b6,#7c3aed)",borderRadius:10,padding:24,color:"#fff",marginBottom:28}}><div style={{fontSize:13,opacity:.8,marginBottom:8}}>Severidad</div><div style={{fontSize:36,fontWeight:700}}>{r.severity||"—"}</div></div>
      <h3 style={{fontSize:16,fontWeight:700,color:"#5b21b6",marginBottom:10}}>Observaciones</h3>
      <div style={{background:"#f8faf9",padding:18,borderRadius:10,fontSize:14,border:"1px solid #e2e8f0",lineHeight:1.7,minHeight:60}}>{ev.observaciones||"Sin observaciones."}</div>
    </div>
  </div>);
}
